"""create_resume_profiles_table

Revision ID: 0f084c119300
Revises: af52fe015ce4
Create Date: 2026-04-20 20:49:55.679415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f084c119300'
down_revision: Union[str, None] = 'af52fe015ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('technologies', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('seniority_level', sa.String(length=50), nullable=True),
    sa.Column('suggested_roles', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('raw_ai_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_profiles')
    # ### end Alembic commands ###
