"""add_job_source_fields

Revision ID: 4695af2ed033
Revises: 1fc94f53158b
Create Date: 2026-04-25 23:49:55.024030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4695af2ed033'
down_revision: Union[str, None] = '1fc94f53158b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('source', sa.String(length=50), server_default='manual', nullable=False))
    op.add_column('job_postings', sa.Column('source_id', sa.String(length=255), nullable=True))
    op.add_column('job_postings', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('job_postings', sa.Column('salary_min', sa.Float(), nullable=True))
    op.add_column('job_postings', sa.Column('salary_max', sa.Float(), nullable=True))
    op.add_column('job_postings', sa.Column('contract_type', sa.String(length=100), nullable=True))
    op.add_column('job_postings', sa.Column('category', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_job_postings_source_source_id', 'job_postings', ['source', 'source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_postings_source_source_id', 'job_postings', type_='unique')
    op.drop_column('job_postings', 'category')
    op.drop_column('job_postings', 'contract_type')
    op.drop_column('job_postings', 'salary_max')
    op.drop_column('job_postings', 'salary_min')
    op.drop_column('job_postings', 'source_url')
    op.drop_column('job_postings', 'source_id')
    op.drop_column('job_postings', 'source')
    # ### end Alembic commands ###
