"""add_job_requirements_fields

Revision ID: 67e737c2f2f3
Revises: fb8e7566e83d
Create Date: 2026-04-29 16:30:52.023819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67e737c2f2f3'
down_revision: Union[str, None] = 'fb8e7566e83d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('required_languages', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('job_postings', sa.Column('experience_requirement', sa.Text(), nullable=True))
    op.add_column('job_postings', sa.Column('salary_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'salary_text')
    op.drop_column('job_postings', 'experience_requirement')
    op.drop_column('job_postings', 'required_languages')
    # ### end Alembic commands ###
