"""add_resume_validation_fields

Revision ID: 7c60e558fbd5
Revises: 4695af2ed033
Create Date: 2026-04-29 00:48:35.986337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c60e558fbd5'
down_revision: Union[str, None] = '4695af2ed033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('is_resume', sa.Boolean(), nullable=True))
    op.add_column('resumes', sa.Column('document_type', sa.String(length=50), nullable=True))
    op.add_column('resumes', sa.Column('validation_confidence', sa.Float(), nullable=True))
    op.add_column('resumes', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'rejection_reason')
    op.drop_column('resumes', 'validation_confidence')
    op.drop_column('resumes', 'document_type')
    op.drop_column('resumes', 'is_resume')
    # ### end Alembic commands ###
