"""add_discovery_columns_to_resume

Revision ID: 832e4510fe90
Revises: c4a8e2f91b0d
Create Date: 2026-05-23 13:35:35.910288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832e4510fe90'
down_revision: Union[str, None] = 'c4a8e2f91b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('discovery_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('resumes', sa.Column('discovery_job_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'discovery_job_count')
    op.drop_column('resumes', 'discovery_status')
    # ### end Alembic commands ###
