"""add_job_enrichment_status

Revision ID: 8d1631e78044
Revises: be9ab1dc83f2
Create Date: 2026-05-01 21:40:56.354063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1631e78044'
down_revision: Union[str, None] = 'be9ab1dc83f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('enrichment_status', sa.String(length=30), nullable=True))
    op.add_column('job_postings', sa.Column('enrichment_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'enrichment_error')
    op.drop_column('job_postings', 'enrichment_status')
    # ### end Alembic commands ###
