"""add_job_enrichment_failure_reason

Revision ID: b8f1095cd566
Revises: 8d1631e78044
Create Date: 2026-05-03 00:51:00.673310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f1095cd566'
down_revision: Union[str, None] = '8d1631e78044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('enrichment_failure_reason', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'enrichment_failure_reason')
    # ### end Alembic commands ###
