"""add_job_source_text

Revision ID: be9ab1dc83f2
Revises: 67e737c2f2f3
Create Date: 2026-04-29 17:28:11.709484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9ab1dc83f2'
down_revision: Union[str, None] = '67e737c2f2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('source_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'source_text')
    # ### end Alembic commands ###
