"""add_job_enrichment_diagnostics

Revision ID: f30841500e46
Revises: b8f1095cd566
Create Date: 2026-05-03 23:57:11.201561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30841500e46'
down_revision: Union[str, None] = 'b8f1095cd566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('enrichment_raw_html_length', sa.Integer(), nullable=True))
    op.add_column('job_postings', sa.Column('enrichment_text_word_count', sa.Integer(), nullable=True))
    op.add_column('job_postings', sa.Column('enrichment_text_preview', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'enrichment_text_preview')
    op.drop_column('job_postings', 'enrichment_text_word_count')
    op.drop_column('job_postings', 'enrichment_raw_html_length')
    # ### end Alembic commands ###
