"""add_resume_client_ip

Revision ID: fb8e7566e83d
Revises: 7c60e558fbd5
Create Date: 2026-04-29 01:51:53.415398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb8e7566e83d'
down_revision: Union[str, None] = '7c60e558fbd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('client_ip', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'client_ip')
    # ### end Alembic commands ###
