from datetime import datetime, timezone

DEMO_JOBS = [
    {
        "title": "Senior Backend Engineer",
        "company": "Acme GmbH",
        "description": "We are looking for a Senior Backend Engineer to join our Vienna-based platform team. You will design and maintain high-performance REST APIs, own our PostgreSQL data layer, and contribute to our migration to an event-driven architecture. You will work closely with product and frontend teams in a fast-moving agile environment.",
        "required_skills": ["Python", "FastAPI", "PostgreSQL", "Docker", "REST APIs", "SQLAlchemy"],
        "required_languages": ["German", "English"],
        "experience_requirement": "3+ years of professional backend development",
        "salary_text": "€55,000 – €75,000 / year",
        "location": "Vienna, Austria",
        "remote": False,
        "contract_type": "permanent",
        "category": "Backend Development",
        "source": "demo",
        "source_id": "demo-001",
        "source_url": None,
        "salary_min": 55000.0,
        "salary_max": 75000.0,
        "posted_at": datetime.now(timezone.utc),
        "enrichment_status": "success",
        "enrichment_failure_reason": None,
    },
    {
        "title": "AI Integration Engineer",
        "company": "TechCorp",
        "description": "TechCorp is hiring an AI Integration Engineer to build LLM-powered features into our SaaS platform. You will work with the Anthropic Claude API and OpenAI to design prompt pipelines, build structured extraction layers, and integrate AI outputs into production Python services. This is a fully remote role open to candidates across Europe.",
        "required_skills": ["Python", "LLM", "Claude API", "OpenAI", "FastAPI", "Prompt Engineering", "REST APIs"],
        "required_languages": ["English"],
        "experience_requirement": "2+ years with Python; any LLM integration experience welcomed",
        "salary_text": "€60,000 – €85,000 / year",
        "location": "Remote",
        "remote": True,
        "contract_type": "permanent",
        "category": "AI Engineering",
        "source": "demo",
        "source_id": "demo-002",
        "source_url": None,
        "salary_min": 60000.0,
        "salary_max": 85000.0,
        "posted_at": datetime.now(timezone.utc),
        "enrichment_status": "success",
        "enrichment_failure_reason": None,
    },
    {
        "title": "Python Developer",
        "company": "StartupXY",
        "description": "StartupXY is a growing Berlin-based startup building developer tooling. We are looking for a Python Developer to extend our Django backend, improve our PostgreSQL schema design, and contribute to our internal REST API platform. We value clean code, good tests, and pragmatic engineering over over-engineering.",
        "required_skills": ["Python", "Django", "PostgreSQL", "Docker", "Git", "REST APIs"],
        "required_languages": ["English"],
        "experience_requirement": "2+ years of Python development",
        "salary_text": "€50,000 – €65,000 / year",
        "location": "Berlin, Germany",
        "remote": False,
        "contract_type": "permanent",
        "category": "Backend Development",
        "source": "demo",
        "source_id": "demo-003",
        "source_url": None,
        "salary_min": 50000.0,
        "salary_max": 65000.0,
        "posted_at": datetime.now(timezone.utc),
        "enrichment_status": "success",
        "enrichment_failure_reason": None,
    },
    {
        "title": "Junior Software Engineer",
        "company": "Wien Digital",
        "description": "Wien Digital develops digital infrastructure for the city of Vienna. We are looking for a Junior Software Engineer with a focus on Java backend services and REST-based client-server systems. You will work in a structured, public-sector environment with experienced mentors, contributing to civic technology that reaches millions of citizens.",
        "required_skills": ["Java", "REST APIs", "SQL", "Git", "OOP"],
        "required_languages": ["German", "English"],
        "experience_requirement": "0–2 years; fresh graduates welcome",
        "salary_text": "€38,000 – €48,000 / year",
        "location": "Vienna, Austria",
        "remote": False,
        "contract_type": "permanent",
        "category": "Software Engineering",
        "source": "demo",
        "source_id": "demo-004",
        "source_url": None,
        "salary_min": 38000.0,
        "salary_max": 48000.0,
        "posted_at": datetime.now(timezone.utc),
        "enrichment_status": "success",
        "enrichment_failure_reason": None,
    },
]
